const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const cities=['Москва','Санкт-Петербург','Новосибирск','Казань','Екатеринбург'];
const branches=[['АО «ТК „МЕГАПОЛИС“»','500301001, Видное, 142718'],['ФИЛИАЛ АО «ТК „МЕГАПОЛИС“» В Г. КРАСНОУФИМСК','661943001, Красноуфимск, 623300'],['ФИЛИАЛ АО «ТК „МЕГАПОЛИС“» В Г. УРЮПИНСК','345743001, Урюпинск, 403112']];
let regState='inn',inn='',selected=null,errors={},timer,pendingRegistration=false,selectedTariff=0;
let form={city:'Россия, Ханты-Мансийский АО, город Сургут',surname:'',name:'',phone:'',email:'',online:'',site:''};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));

const solutionData={shop:{title:'Интернет-магазинам',items:['Примерка','Частичный выкуп','Наложенный платёж','Страхование'],color:'#c9f8fb',side:[['Интеграции','Автоматизируйте рутину'],['Возвраты','Проверим и вернём товары'],['Приём платежей','Без комиссии 3 месяца'],['Digital реклама','Покажите рекламу 12 млн клиентов']]},market:{title:'Маркетплейсам',items:['Поставка точно в слот','Доставка на все склады','Проверка маркировки','Возврат товара'],color:'#fff0c7',side:[['FBO и FBS','Работаем с любыми схемами'],['Упаковка','Подготовим к приёмке'],['Аналитика','Контроль поставок'],['Забор груза','От двери до склада']]},abroad:{title:'Зарубежные поставки',items:['Документы и таможня','Доставка от двери','Отслеживание','Персональный менеджер'],color:'#d8e9ff',side:[['Импорт','Привезём товары'],['Экспорт','Отправим клиентам'],['Китай','Прямые маршруты'],['Документы','Поможем оформить']]},heavy:{title:'Тяжёлые грузы',items:['От 30 кг','Паллетные перевозки','Межтерминальная доставка','Страхование'],color:'#e3dcff',side:[['Склад','Ответственное хранение'],['Забор','Подадим машину'],['Экспресс','Ускоренная доставка'],['Контроль','Отслеживание маршрута']]}};
function renderSolution(key='shop'){const d=solutionData[key];$$('[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===key));$('#solution-content').innerHTML=`<div class="solution-grid"><article class="solution-main" style="background:${d.color}"><h3>${d.title}</h3><ul>${d.items.map(x=>`<li>${x}</li>`).join('')}</ul><button class="light-btn">Подробнее</button><img src="assets/landing/solutions.png" alt=""></article>${d.side.map(x=>`<article class="solution-card"><h3>${x[0]}</h3><p>${x[1]}</p><button class="round-arrow">→</button></article>`).join('')}</div>`}
function scrollToSection(id){const el=$('#'+id);window.scrollTo({top:Math.max(0,el.offsetTop-105),behavior:'smooth'})}
$$('[data-tab]').forEach(b=>b.onclick=()=>renderSolution(b.dataset.tab));$$('[data-solution]').forEach(b=>b.onclick=()=>{renderSolution(b.dataset.solution);scrollToSection('business')});renderSolution();

function tariffSeed(a,b){return ([...a].reduce((n,c)=>n+c.charCodeAt(0),0)*3+[...b].reduce((n,c)=>n+c.charCodeAt(0),0)*7)%9}
function renderTariffs(){const a=$('#from-city').value,b=$('#to-city').value,n=tariffSeed(a,b),base=250+n*35;$('#tariffs').innerHTML=[[base,5],[base+500,3],[base+1000,1]].map((x,i)=>`<button class="tariff ${i===selectedTariff?'selected':''}" data-tariff="${i}"><span class="tariff-art t${i}"></span>${i===selectedTariff?'<img class="tariff-check" src="assets/landing/check-circle.svg" alt="Выбрано">':''}<b>от ${x[0].toLocaleString('ru-RU')} ₽</b><small>${x[1]} ${x[1]===1?'день':x[1]===5?'дней':'дня'}</small></button>`).join('');$$('[data-tariff]').forEach(b=>b.onclick=()=>{selectedTariff=+b.dataset.tariff;renderTariffs()})}
$$('.city-menu').forEach(m=>m.innerHTML=cities.map(c=>`<button type="button">${c}</button>`).join(''));
$$('.city-menu button').forEach(b=>b.onmousedown=e=>{e.preventDefault();const input=$('#'+b.parentElement.dataset.menu);input.value=b.textContent;renderTariffs();input.blur()});
$$('.city-control input').forEach(i=>i.oninput=renderTariffs);$$('[data-clear]').forEach(b=>b.onmousedown=e=>{e.preventDefault();const i=$('#'+b.dataset.clear);i.value='';renderTariffs();i.focus()});
$('#swap-cities').onclick=()=>{const a=$('#from-city'),b=$('#to-city'),v=a.value;a.value=b.value;b.value=v;renderTariffs()};renderTariffs();
$$('[data-scroll]').forEach(b=>b.onclick=()=>scrollToSection(b.dataset.scroll));
['#brand-home','#business-home'].forEach(selector=>$(selector).onclick=()=>window.scrollTo({top:0,behavior:'smooth'}));

function steps(){const step=regState==='form'?2:['auth','creating','success'].includes(regState)?3:1;return `<div class="steps"><button class="step ${step>1?'complete':step===1?'current':''}" data-back="company"><span class="num">${step>1?'✓':'1'}</span><span><strong>Укажите компанию</strong><small>По ИНН</small></span></button><button class="step ${step>2?'complete':step===2?'current':''}" ${selected===null?'disabled':''} data-back="form"><span class="num">${step>2?'✓':'2'}</span><span><strong>Заполните анкету</strong><small>Всего за 3 минуты</small></span></button><button class="step ${step===3?'current':''}" disabled><span class="num">3</span><span><strong>Войдите в кабинет</strong><small>Отправляйте посылки уже сегодня</small></span></button></div>`}
function field(n,label,type='text'){return `<div><label class="field ${errors[n]?'invalid':''}"><span>${label}</span><input name="${n}" type="${type}" value="${esc(form[n])}" autocomplete="off"></label>${errors[n]?`<div class="error">${errors[n]}</div>`:''}</div>`}
function regContent(){if(regState==='inn'||regState==='searching')return `<form id="inn-form"><label class="search-label">Введите ИНН компании или ИП</label><div class="search-row"><label class="field"><span>Введите ИНН компании или ИП</span><input id="inn" inputmode="numeric" value="${esc(inn)}" ${regState==='searching'?'disabled':''}></label><button class="search-go" ${regState==='searching'?'disabled':''}>${regState==='searching'?'<span class="spinner"></span>':'→'}</button></div>${errors.inn?`<div class="error">${errors.inn}</div>`:''}</form>`;
if(regState==='branches')return `<div class="branches"><h3>Выберите филиал</h3>${branches.map((b,i)=>`<button class="branch" data-branch="${i}"><span><strong>${b[0]}</strong><small>КПП ${b[1]}</small></span><b>→</b></button>`).join('')}</div>`;

if(regState==='creating')return `<div class="reg-status"><span class="spinner"></span><h3>Создаём кабинет</h3><p>Подписываем договор и отправляем письмо с логином.</p></div>`;
if(regState==='success')return `<div class="reg-status"><div class="art">💼🔑</div><h3>Компания зарегистрирована</h3><p>На почту ${esc(form.email)} отправили номер договора, который станет вашим логином, и ссылку для создания пароля</p><button class="green-btn" id="enter-cabinet">Войти в кабинет</button></div>`;
const b=branches[selected];return `<button class="back-link" data-back="company">← Вернуться к выбору компании</button><div class="selected"><strong>${b[0]}</strong><small>КПП ${b[1]}</small></div><h3 class="form-title">Укажите контактные данные</h3><form class="reg-form" id="reg-form"><div class="fields">${field('city','Город')}${field('surname','Фамилия')}${field('name','Имя')}${field('phone','Телефон','tel')}${field('email','Email','email')}</div><fieldset class="online-choice"><legend>Компания продаёт товары онлайн?</legend><p class="online-hint">От ответа зависят тип договора, доступные услуги и условия доставки</p><div class="radio-row"><label><input type="radio" name="online" value="yes" ${form.online==='yes'?'checked':''}> Да, продаём онлайн</label><label><input type="radio" name="online" value="no" ${form.online==='no'?'checked':''}> Нет, не продаём онлайн</label></div>${errors.online?`<div class="error">${errors.online}</div>`:''}${form.online==='yes'?`<div class="website">${field('site','Ссылка на магазин или страницу с товарами')}<p class="online-hint">Подойдёт сайт, страница на маркетплейсе, в соцсети или объявление на Авито</p></div>`:''}</fieldset><button class="green-btn submit">Зарегистрироваться</button><p class="legal">Нажимая «Зарегистрироваться», я принимаю условия договора и даю согласие на обработку персональных данных</p></form>`}
function renderReg(){const app=$('#registration-app');app.innerHTML=`${steps()}<div class="reg-shell"><div class="reg-panel">${regContent()}</div><aside class="offer"><b>Оформление договора онлайн</b>Без поездок в офис и бумажных документов</aside></div>`;wireReg()}
function wireReg(){const innForm=$('#inn-form');if(innForm){$('#inn').oninput=e=>{inn=e.target.value};innForm.onsubmit=e=>{e.preventDefault();if(!inn.trim()){e.target.querySelector('input').focus();return}errors={};regState='searching';renderReg();timer=setTimeout(()=>{regState='branches';renderReg()},1000)}}$$('[data-branch]').forEach(b=>b.onclick=()=>{selected=+b.dataset.branch;regState='form';renderReg()});$$('[data-back=company]').forEach(b=>b.onclick=()=>{if(regState!=='inn'){regState=selected===null?'inn':'branches';renderReg()}});$$('[data-back=form]').forEach(b=>b.onclick=()=>{if(selected!==null){regState='form';renderReg()}});const f=$('#reg-form');if(f){f.oninput=e=>{if(e.target.name&&e.target.name!=='online')form[e.target.name]=e.target.value};$$('[name=online]').forEach(r=>r.onchange=e=>{form.online=e.target.value;if(form.online==='no')form.site='';renderReg()});f.onsubmit=e=>{e.preventDefault();errors={};['city','surname','name','phone','email'].forEach(n=>{if(!form[n].trim())errors[n]='Нужно заполнить поле'});if(!form.online)errors.online='Выберите вариант';if(form.online==='yes'&&!form.site.trim())errors.site='Нужно заполнить поле';if(form.email&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(form.email))errors.email='Введите корректный email';if(Object.keys(errors).length){renderReg();return}pendingRegistration=true;openAuth()}}$$('[data-login]').forEach(b=>b.onclick=openAuth);if($('#enter-cabinet'))$('#enter-cabinet').onclick=openCabinet}

function openAuth(){const s=$('#auth-screen');s.hidden=false;s.innerHTML=`<div class="auth-center"><div class="auth-card"><button class="back-auth" id="close-auth">‹</button><img src="assets/logo.svg" alt="CDEK"><h2>Войдите, чтобы продолжить</h2><div class="search-row"><label class="field"><span>Телефон</span><input id="auth-phone" value="${esc(form.phone||'9122875647')}"></label></div><label style="display:flex;gap:8px;margin:14px 0"><input type="checkbox" checked> Запомнить меня</label><div class="captcha">Л7ер</div><label class="field"><span>Введите текст с картинки</span><input id="captcha"></label><button class="green-btn" id="get-code">Получить код</button><p class="legal">Продолжая, вы соглашаетесь с Пользовательским соглашением</p></div></div>`;$('#close-auth').onclick=closeAuth;$('#get-code').onclick=()=>{const c=$('.auth-card');c.innerHTML=`<button class="back-auth" id="close-auth">‹</button><img src="assets/logo.svg" alt="CDEK"><h2>Введите код из СМС</h2><p>Код отправлен на +7 ${esc($('#auth-phone')?.value||form.phone)}</p><label class="field"><span>Код из СМС</span><input id="sms-code" inputmode="numeric" value="1234"></label><button class="green-btn" id="auth-submit">Войти</button>`;$('#close-auth').onclick=closeAuth;$('#auth-submit').onclick=finishAuth}}
function closeAuth(){$('#auth-screen').hidden=true}
function finishAuth(){closeAuth();if(pendingRegistration){regState='creating';renderReg();$('#register').scrollIntoView();timer=setTimeout(()=>{regState='success';pendingRegistration=false;renderReg()},1600)}else openCabinet()}
function openCabinet(){const s=$('#cabinet-screen');s.hidden=false;s.innerHTML=`<div class="cabinet-top"><img src="assets/cabinet-logo.svg" alt="CDEK" height="36"><button class="dark-btn" id="close-cabinet">Закрыть кабинет</button></div><div class="cabinet-page"><aside class="cabinet-nav"><h3>Константин</h3><p>Новосибирск</p><hr><b>⌂ Главная</b><p>Программа лояльности</p><p>Онлайн-оплата</p><p>Электронные чеки</p><p>Помощь</p></aside><main class="cabinet-content"><h1>Заказы</h1><div class="empty-orders"><div><img src="assets/orders-empty.png" alt=""><h2>Пока нет заказов</h2><button class="green-btn">Создать заказ</button></div></div></main></div>`;$('#close-cabinet').onclick=()=>s.hidden=true}

renderReg();
